- name: cofigure  Centos 7  server  yum repo
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - Centos-7.repo
    - epel-7.repo
    - zabbix.repo
  when: ansible_distribution == "CentOS"  and   ansible_distribution_major_version == "7"

- name : cofigure  Centos 6  server  yum repo 
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: 
    - Centos-6.repo
    - epel-6.repo
    - zabbix.repo
  when: ansible_distribution == "CentOS"  and   ansible_distribution_major_version == "6"
- name: sure /root/.pip directory
  file:
    path: /root/.pip
    state: directory
- name: update pip repo
  copy:
    src: pip.conf
    dest: /root/.pip/pip.conf
    owner: root
    group: root
    mode: 0644
