
- name: update yum  zabbix rpm
  shell: rpm -ivh http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
  #ignore_errors: True
- name: install zabbix agent
  package:
    name:  zabbix-agent 
    state: present
- name: Copy zabbix_agentd.conf 
  template: 
     src: zabbix_agentd.conf.j2 
     dest: /etc/zabbix/zabbix_agentd.conf 
     owner: root 
     group: root 
     mode: 0644
  notify:  restart  zabbix agent service
- name: start zabbix_agent service
  service: 
    name: zabbix-agent 
    state: started 
    enabled: yes 
